SELECT COUNT(UserId) FROM USER;

SELECT DISTINCT Type FROM DEVICE;

SELECT Name, PlanType FROM USER
ORDER BY RegistrationDate DESC
LIMIT 1;

SELECT PLAYLIST.Title, COUNT(PLAYED.PlaylistID) as Num FROM PLAYED JOIN PLAYLIST ON PLAYED.PlaylistID=PLAYLIST.PlaylistID
GROUP BY PLAYED.PlaylistID
ORDER BY Num DESC;

SELECT AVG(UEDownloads) FROM SONG;

SELECT Genre, COUNT(SongID) as Num
FROM SONG
GROUP BY Genre
ORDER BY NUM Desc;

SELECT DISTINCT(PLAYLIST.Title), PLAYLIST.CreationDate FROM (PLAYLIST JOIN BELONGS ON PLAYLIST.PlaylistID = BELONGS.PlaylistID
JOIN SONG ON SONG.SongID= BELONGS.SongID JOIN ARTIST ON ARTIST.SongID=SONG.SongID)
WHERE Artist='Taylor Swift' AND YEAR(CreationDate)>2019
ORDER BY PLAYLIST.Title;